<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Version>0.1.0</Version>
    <AssemblyName>EvilFarmOwner</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="i18n\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
